# -*- coding: utf-8 -*-
"""Modul_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zHvNMd_QsIGUgnfoB8uE8dclFyRHbHJ0
"""

print("Hello world!")

print("Hands-on Data Viz with Python ")

#int (sayıları temsil eder)
x = 100 
print(x)

#float (ondalıklı sayıları temsil eder)
num = 2.5 
print("Num degerimiz : ", num)

#str (yazıları ve stringleri temsil eder)
string = 'a'
print(string)

type(string) #Elimizdeki verinin hangi veri tipine sınıfına ait olduğunu öğrenmemizi sağlıyor

type(num)

type(x)

type(3)

3 + 5

"3"+"5" # concat

3 * 5

num * 5

print(x // 5)

num / 3

num //3

round(1.1)

round(2.5)

round(2.6)

x = 10 
print(x + 2)
print(x - 2)
print(x * 2)
print(x / 2)
print(x % 2)
print(x // 2)

paragraf = """ Global AI Hub İsviçre Merkezli günden güne büyüyen Yapay Zeka Topluluğudur """

print(paragraf)

'''
Erdem YAZAN
Gizem YAZAN
'''

print("Erdem" + "Yazan")

user_name = "erdem"
age = 28 
print("User Name : ", user_name, "Age : ", age)

type(age)

float(age)

integer_value = int(2.5)
string_value = str(2)
string_value

int('3')

merhaba = 'merhaba dünya'

print(f'Hosgeldiniz', {merhaba})

string1 = 'İstanbul'
print(string1[0])

string1[0:5]

string1[0:8]

string1[0:5:2]

erdem = True 
gizem = False

print(10>9)

print(10 == 3)

liste = ['2','erdem',2,2.5,True,'Global AI']
print(liste)

scores = [44,48,55,89,34]

scores.append(100)
print(scores)

# append değeri sona ekler. 
scores.append(100)

print(scores)

scores.insert(3,7)

print(scores)

# Extend elimizdeki veriyi genişletmeye yarar
scores.extend([23])

print(scores)

print(scores.pop())

print(scores)

scores.remove(89)
print(scores)

scores.clear()
print(scores)

#indexler üzerinde çalışmak (index, count)
alphabet = ['a','b','c','d','e','f','f','f']
print(alphabet.index('a'))

print(alphabet.index('f'))

print(alphabet.count('a'))

print(alphabet.count('f'))

# sort, reverse, copy 
number = [1, 2, 39, 3, 21, 44, 12]

print(number.sort())

number.sort()
number

number.reverse()

number

number2 = number.copy()
number2

sorted(number)
#sorted kalıcı değil

#Dictionary
user = {'name': 'Erdem', 'Age' : 28, 'married': True}

user

user['Basari'] = 'Calismak'

user

print(user['married'])
print(user['Age'])
print(user['Basari'])

#key operatorü
print('name' in user.keys())

user.keys()

erdem = [25,44,5.6]
print(25 in erdem)

#sadece iterasyon yapabildiğimiz değerlerde kullanabilir miyiz?